#include "vector_utils.h"
#include <stdlib.h>

/**
 * Generates a random number between min and max.
 * The number sequence generated by the fuction rand is always the 
 * same because it uses the defaulta seed 0.
 */
int get_random (int min, int max) {
    return rand() % (max - min + 1) + min;
}

/**
 * Starts the vector with random values belonging to the interval [min..max]
 */
void vector_init_rand (int v[], long dim, int min, int max) {
    for (long i = 0; i < dim; i++)
        v[i] = get_random(min, max);
}