#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/time.h>

#define LOWER_LIMIT       0
#define UPPER_LIMIT     100

/**
 * Generates a random number between min and max.
 * The number sequence generated by the fuction rand is always the 
 * same because it uses the defaulta seed 0.
 */
int get_random (int min, int max) 
{
    return rand() % (max - min + 1) + min;
}

/**
 * Starts the vector with random values belonging to the interval [min..max]
 */
void vector_init_rand (int v[], long dim, int min, int max)
{
    for (long i = 0; i < dim; i++) {
        v[i] = get_random(min, max);
    }
}

/**
 * Gets the subvector of values in the range [min..max]
 * 
 * returns the number of values store in subvector sv 
 */
int vector_get_in_range(int v[], int v_sz, int sv[], int min, int max, int n_processes){
    int pipefd[n_processes][2];
    pid_t retfork[n_processes];
    int subarray_size = v_sz / n_processes;

    for (int i = 0; i < n_processes; i++){
        if (pipe(pipefd[i]) == -1) {
            perror("pipe");
            exit(1);
        }

        retfork[i] = fork();

        if (retfork[i] < 0){
            perror("fork");
            exit(1);
        }
        else if(retfork[i] == 0){
            close(pipefd[i][0]);

            for (int j = i * subarray_size; j < (i + 1) * subarray_size; j++) {
                if (v[j] >= min && v[j] <= max) {
                    write(pipefd[i][1], &v[j], sizeof(int));  // Send element to parent process
                }
            }

            close(pipefd[i][1]);
            exit(0);
        }

        close(pipefd[i][1]);
    }

    int num_elements = 0;
    for (int i = 0; i < n_processes; i++) {
        int element;
        
        while (read(pipefd[i][0], &element, sizeof(int)) > 0) {
            sv[num_elements] = element;
            num_elements++;
        }
        
        close(pipefd[i][0]);
    }

    return num_elements;
}

int main(int argc, char *argv[]){
    if (argc < 3) {
        printf("Usage: %s <vector dimension> <number processes>\n", argv[0]);
        exit(1);
    }

    long values_sz = atol(argv[1]);
    int n_processes = atoi(argv[2]);

    printf("Initializing a vector of %ld bytes\n", values_sz);

    // allocate a vector of initial values
    int *values = malloc(sizeof(int) * values_sz);
    if (values == NULL) {
        fprintf(stderr, "Erro malloc\n");
        return -1;
    }

    // allocate a subvector where will be store values in a interval of values
    int *subvalues = malloc(sizeof(int) * values_sz);
    if (subvalues == NULL) {
        fprintf(stderr, "Erro malloc\n");
        return -1;
    }

    // initiate initial array of values 
    vector_init_rand(values, values_sz, LOWER_LIMIT, UPPER_LIMIT);

    struct timeval t1,t2;
    gettimeofday(&t1, NULL);

    // start of code to evaluate

    long count     = 0;
    int values_min = 50;
    int values_max = 100;

    count = vector_get_in_range(values, values_sz, subvalues, values_min, values_max, n_processes);

    // end of code to evaluate

    gettimeofday(&t2, NULL);
    long elapsed = ((long)t2.tv_sec - t1.tv_sec) * 1000000L + (t2.tv_usec - t1.tv_usec);
    long sec = elapsed / (long)1e6;
    long aux = elapsed % (long)1e6;
    long mil = aux / (long)1e3;
    long mic = aux % (long)1e3;
     

    printf ("Elapsed time = %lds%ld,%ldms\n", sec, mil, mic);

    printf("Values between [%d..%d]: %ld\n", values_min, values_max, count);

    return 0;
}